apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.cilium.io
    chart: cilium
    targetRevision: '*'
    helm:
      values: |
        kubeProxyReplacement: strict
        k8sServiceHost: kind-external-load-balancer
        k8sServicePort: 6443
        hostServices:
          enabled: true
        externalIPs:
          enabled: true
        nodePort:
          enabled: true
        hostPort:
          enabled: true
        image:
          pullPolicy: IfNotPresent
        ipam:
          mode: kubernetes
        operator:
          prometheus:
            enabled: true
            serviceMonitor:
              enabled: true
        prometheus:
          enabled: true
          serviceMonitor:
            enabled: true
        hubble:
          enabled: true
          metrics:
            enabled:
              - dns:query;ignoreAAAA
              - drop
              - tcp
              - flow
              - icmp
              - http
            serviceMonitor:
              enabled: true
          relay:
            enabled: true
          ui:
            enabled: true
            ingress:
              enabled: true
              annotations:
                kubernetes.io/ingress.class: nginx
                cert-manager.io/cluster-issuer: ca-issuer
              hosts:
                - hubble-ui.kind.cluster
              tls:
                - secretName: hubble-ui.kind.cluster
                  hosts:
                    - hubble-ui.kind.cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  revisionHistoryLimit: 3
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - FailOnSharedResource=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
