apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: keycloak
    targetRevision: '*'
    helm:
      values: |
        auth:
          createAdminUser: true
          adminUser: admin
          adminPassword: admin
          managementUser: manager
          managementPassword: manager
        proxyAddressForwarding: true
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
        ingress:
          enabled: true
          hostname: keycloak.kind.cluster
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: ca-issuer
          tls: true
          selfSigned: false
        podSecurityContext:
          runAsNonRoot: true
        containerSecurityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
        postgresql:
          enabled: true
          postgresqlPassword: password
          securityContext:
            runAsNonRoot: true
          containerSecurityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
            securityContext:
              runAsNonRoot: true
            containerSecurityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
              runAsNonRoot: true
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  revisionHistoryLimit: 3
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - FailOnSharedResource=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
