apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno
    chart: kyverno-policies
    targetRevision: '*'
    helm:
      values: |
        podSecurityStandard: restricted
        validationFailureAction: audit
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  revisionHistoryLimit: 3
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - FailOnSharedResource=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: kyverno.io
      kind: ClusterPolicy
      jqPathExpressions:
        - .spec.rules[] | select(.name|test("autogen-."))
